// infrastructure/entry-points/reactive-web/build.gradle
dependencies {
    implementation project(':usecase')
    implementation project(':model')
    implementation project(':r2dbc-postgresql')

    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'io.micrometer:micrometer-registry-prometheus'

    // MapStruct para mappers REST
    implementation "org.mapstruct:mapstruct:$mapstructVersion"
    annotationProcessor "org.mapstruct:mapstruct-processor:$mapstructVersion"

    // Testing dependencies para WebFlux
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-test-autoconfigure'
    testImplementation 'org.mockito:mockito-core'
    testImplementation 'org.mockito:mockito-junit-jupiter'

    // Excluir BlockHound de reactor-test
    testImplementation('io.projectreactor:reactor-test') {
        exclude group: 'io.projectreactor.tools', module: 'blockhound'
    }
}

test {
    useJUnitPlatform()
    systemProperty 'junit.jupiter.execution.parallel.enabled', false
    systemProperty 'reactor.blockhound.integration.disabled', 'true'
    jvmArgs = [
            '--add-opens', 'java.base/java.lang=ALL-UNNAMED',
            '--add-opens', 'java.base/java.util=ALL-UNNAMED',
            '-XX:+AllowRedefinitionToAddDeleteMethods'
    ]
}