// domain/model/build.gradle

description = 'Domain Model - Entidades y Gateways puros'

dependencies {

    // Testing básico sin dependencias externas
    testImplementation 'org.junit.jupiter:junit-jupiter:5.11.4'
    testImplementation 'org.assertj:assertj-core:3.26.3'

}

test {
    useJUnitPlatform()
}