// domain/model/build.gradle

description = 'Domain Model - Entidades y Gateways puros'

dependencies {

    // Testing básico sin dependencias externas
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.assertj:assertj-core:3.24.2'

}

test {
    useJUnitPlatform()
    systemProperty 'junit.jupiter.execution.parallel.enabled', false
    systemProperty 'reactor.blockhound.integration.disabled', 'true'
    jvmArgs = [
            '--add-opens', 'java.base/java.lang=ALL-UNNAMED',
            '--add-opens', 'java.base/java.util=ALL-UNNAMED',
            '-XX:+AllowRedefinitionToAddDeleteMethods'
    ]
}