# ============================================================
# microservicio-solicitudes/gradle.properties
# ============================================================
package=com.crediya.solicitudes
systemProp.version=3.25.0
reactive=true
lombok=true
metrics=true
language=java

lombokVersion=1.18.38
mapstructVersion=1.6.3
springBootVersion=3.5.4
jacocoVersion=0.8.13
pitestVersion=1.19.0-rc.1

org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.configuration-cache.integrity-check=true
systemProp.sonar.gradle.skipCompile=true

# gradle.properties
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.configureondemand=false

# Para evitar warnings de Java Agent
systemProp.jdk.instrument.traceUsage=false
systemProp.java.awt.headless=true