// domain/usecase/build.gradle
description = 'Domain Use Cases - Lógica de negocio pura'

dependencies {
    implementation project(':model')

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation('io.projectreactor:reactor-test') {
        exclude group: 'io.projectreactor.tools', module: 'blockhound'
    }
    testImplementation 'org.assertj:assertj-core:3.24.2'
}

test {
    useJUnitPlatform()
    systemProperty 'junit.jupiter.execution.parallel.enabled', false
    systemProperty 'reactor.blockhound.integration.disabled', 'true'
    jvmArgs = [
            '--add-opens', 'java.base/java.lang=ALL-UNNAMED',
            '--add-opens', 'java.base/java.util=ALL-UNNAMED',
            '-XX:+AllowRedefinitionToAddDeleteMethods'
    ]
}
// Configuración específica de PIT para el módulo usecase
pitest {
    targetClasses = ['com.crediya.solicitudes.usecase.crearsolicitud.CrearSolicitudUseCase']
    targetTests = ['com.crediya.solicitudes.usecase.crearsolicitud.CrearSolicitudUseCaseTest']

    // Excluir integration tests
    excludedTestClasses = [
            '*IntegrationTest*',
            '*Integration*',
            'com.crediya.solicitudes.usecase.crearsolicitud.CrearSolicitudIntegrationTest'
    ]

    // Configuración específica para UseCase
    mutationThreshold = 85
    coverageThreshold = 95
    threads = 2
    verbose = true
}