// domain/usecase/build.gradle
description = 'Domain Use Cases - Lógica de negocio pura'

dependencies {
    implementation project(':model')

    // Usar Spring Boot Test que ya está alineado en el proyecto
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation('io.projectreactor:reactor-test') {
        exclude group: 'io.projectreactor.tools', module: 'blockhound'
    }
    testImplementation 'org.assertj:assertj-core:3.24.2'
}

test {
    useJUnitPlatform()
    systemProperty 'junit.jupiter.execution.parallel.enabled', false
    systemProperty 'reactor.blockhound.integration.disabled', 'true'
    jvmArgs = [
            '--add-opens', 'java.base/java.lang=ALL-UNNAMED',
            '--add-opens', 'java.base/java.util=ALL-UNNAMED',
            '-XX:+AllowRedefinitionToAddDeleteMethods'
    ]
}