server:
  port: 8080

spring:
  application:
    name: "MicroservicioSolicitudes"
  devtools:
    add-properties: false

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/crediya_solicitudes
    user: postgres
    password: superapostgres
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: true

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

# ✅ CONFIGURACIÓN R2DBC POSTGRESQL
adapters:
  r2dbc:
    postgresql:
      host: localhost
      port: 5432
      database: crediya_solicitudes
      schema: public
      username: postgres
      password: superapostgres