// applications/app-service/build.gradle
apply plugin: 'org.springframework.boot'

dependencies {
	implementation project(':r2dbc-postgresql')
	implementation project(':reactive-web')
	implementation 'org.reactivecommons.utils:object-mapper:0.1.0'
    implementation project(':model')
    implementation project(':usecase')

    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-data-r2dbc'

    runtimeOnly('org.springframework.boot:spring-boot-devtools')

    // Testing
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.mockito:mockito-core'
    testImplementation 'org.mockito:mockito-junit-jupiter'
    testImplementation 'com.tngtech.archunit:archunit:1.4.1'
    testImplementation 'com.fasterxml.jackson.core:jackson-databind'

    // Excluir BlockHound de reactor-test
    testImplementation('io.projectreactor:reactor-test') {
        exclude group: 'io.projectreactor.tools', module: 'blockhound'
    }
}

tasks.register('explodedJar', Copy) {
    with jar
    into layout.buildDirectory.dir("exploded")
}

jar {
    // To disable the *-plain.jar
    enabled = false
}

bootJar {
    // Sets output jar name
    archiveFileName = "${project.getParent().getName()}.${archiveExtension.get()}"
}

test {
    useJUnitPlatform()
    systemProperty 'junit.jupiter.execution.parallel.enabled', false
    systemProperty 'reactor.blockhound.integration.disabled', 'true'
    jvmArgs = [
            '--add-opens', 'java.base/java.lang=ALL-UNNAMED',
            '--add-opens', 'java.base/java.util=ALL-UNNAMED',
            '-XX:+AllowRedefinitionToAddDeleteMethods'
    ]
}